fix: change folder capitalization
There was a problem when changing the cap of the folders abruptly.

Error: Prevent writing to file that only differs in casing or query string

To solve the issue we need to rename the folder or file to a temp name, commit the changes and then again rename the files to the name we want

see here https://stackoverflow.com/questions/51197940/file-name-differs-from-already-included-file-name-only-in-casing-on-relative-p